apiVersion: v1
kind: Service
metadata:
  name: demo-client
  labels:
    app.kubernetes.io/name: demo-client
    app.kubernetes.io/component: demo
    app.kubernetes.io/part-of: janus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-client
  ports:
    - name: http
      port: 8091
      targetPort: 8091
