apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: janus

resources:
  - ns.yaml
  - postgres
  - redis
  - prometheus
  - grafana
  - policy-store
  - state-store
  - evaluator
  - admin-ui
