spring:
  application:
    name: demo-client
  grpc:
    client:
      channels:
        sidecar:
          address: localhost:9094

server:
  port: 8091

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

janus:
  sdk:
    enabled: true
    sidecar-channel: sidecar
    refresh-interval: 5s