apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: janus
type: Opaque
stringData:
  POSTGRES_DB: janus-policy-store-db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
