spring:
  application:
    name: policy-store
  grpc:
    server:
      port: 9090
  datasource:
    url: jdbc:postgresql://postgres:5432/janus-policy-store-db
    username: postgres
    password: postgres