spring:
  grpc:
    server:
      port: 9091
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
  h2:
    console:
      enabled: true

logging:
  level:
    org.janus.policystore: DEBUG