spring:
  grpc:
    server:
      port: 9092
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s

server:
  port: 8082

management:
  server:
    port: 8082

logging:
  level:
    org.janus.statestore: DEBUG